# Core
db:
  redis:
    host: 'arc_users'
    port: 6379
    namespace: EG
    
cli:   
  url: http://localhost:9876

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
  
plugins:
  rewrite:
    package: express-gateway-plugin-rewrite
